#!/bin/sh
a_flag=FALSE
b_flag=FALSE

while getopts e option
do case $option in 
a) a_flag=true;;
b) b_flag=true;;
l) logfiles=${OPTARG};;
\?) echo -u2 "Usage ${prog_name} [ -a -b -l logfile_name ]"
exit 2;;
esac
done

echo 123
echo ${a_flag}
echo ${b_flag}
echo ${LOGFILE}
